### Guard::Qu
#  available options:
#  - :task (defaults to 'qu:work' if :count is 1; 'qu:workers', otherwise)
#  - :verbose / :vverbose (set them to anything but false to activate their respective modes)
#  - :trace
#  - :queue (defaults to "*")
#  - :count (defaults to 1)
#  - :environment (corresponds to RACK_ENV for the Qu worker)
guard 'qu', :environment => 'development' do
  watch(%r{^app/(.+)\.rb$})
  watch(%r{^lib/(.+)\.rb$})
end
