### Guard::Qu
#  available options:
#  - :task (defaults to 'qu:work')
#  - :trace
#  - :queue (defaults to "default")
#  - :environment (corresponds to RACK_ENV for the Qu worker)
guard 'qu', :environment => 'development' do
  watch(%r{^app/(.+)\.rb$})
  watch(%r{^lib/(.+)\.rb$})
end
